export const works = [
  {
    src: '/images/portfolio/private-001.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-002.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-003.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-004.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-005.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-006.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-007.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-008.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-009.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-010.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-011.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-012.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-013.webp',
    category: 'private',
    subcategoryKey: '26-4-1-悉尼歌剧院',
    subcategoryZh: '26 4 1 悉尼歌剧院',
    subcategoryEn: 'Opera House session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-014.jpg',
    category: 'private',
    subcategoryKey: '26-5-14-刘文刀-北大-个人-悉大',
    subcategoryZh: '26 5 14 刘文刀 北大 个人 悉大',
    subcategoryEn: 'USYD personal session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-015.jpg',
    category: 'private',
    subcategoryKey: '26-5-14-刘文刀-北大-个人-悉大',
    subcategoryZh: '26 5 14 刘文刀 北大 个人 悉大',
    subcategoryEn: 'USYD personal session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-016.jpg',
    category: 'private',
    subcategoryKey: '26-5-14-刘文刀-北大-个人-悉大',
    subcategoryZh: '26 5 14 刘文刀 北大 个人 悉大',
    subcategoryEn: 'USYD personal session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-017.jpg',
    category: 'private',
    subcategoryKey: '26-5-14-刘文刀-北大-个人-悉大',
    subcategoryZh: '26 5 14 刘文刀 北大 个人 悉大',
    subcategoryEn: 'USYD personal session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-018.jpg',
    category: 'private',
    subcategoryKey: '26-5-14-刘文刀-北大-个人-悉大',
    subcategoryZh: '26 5 14 刘文刀 北大 个人 悉大',
    subcategoryEn: 'USYD personal session',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-019.jpg',
    category: 'private',
    subcategoryKey: '26-5-7-谢礼谦-个人-unsw毕业照约拍',
    subcategoryZh: '26 5 7 谢礼谦 个人 UNSW毕业照约拍',
    subcategoryEn: 'UNSW graduation session',
    zhTitle: '毕业照约拍',
    enTitle: 'Graduation session',
    featured: true,
  },
  {
    src: '/images/portfolio/private-020.jpg',
    category: 'private',
    subcategoryKey: '26-5-7-谢礼谦-个人-unsw毕业照约拍',
    subcategoryZh: '26 5 7 谢礼谦 个人 UNSW毕业照约拍',
    subcategoryEn: 'UNSW graduation session',
    zhTitle: '毕业照约拍',
    enTitle: 'Graduation session',
  },
  {
    src: '/images/portfolio/private-021.jpg',
    category: 'private',
    subcategoryKey: '26-5-7-谢礼谦-个人-unsw毕业照约拍',
    subcategoryZh: '26 5 7 谢礼谦 个人 UNSW毕业照约拍',
    subcategoryEn: 'UNSW graduation session',
    zhTitle: '毕业照约拍',
    enTitle: 'Graduation session',
  },
  {
    src: '/images/portfolio/private-022.jpg',
    category: 'private',
    subcategoryKey: '26-5-7-谢礼谦-个人-unsw毕业照约拍',
    subcategoryZh: '26 5 7 谢礼谦 个人 UNSW毕业照约拍',
    subcategoryEn: 'UNSW graduation session',
    zhTitle: '毕业照约拍',
    enTitle: 'Graduation session',
  },
  {
    src: '/images/portfolio/private-023.jpg',
    category: 'private',
    subcategoryKey: '26-5-7-谢礼谦-个人-unsw毕业照约拍',
    subcategoryZh: '26 5 7 谢礼谦 个人 UNSW毕业照约拍',
    subcategoryEn: 'UNSW graduation session',
    zhTitle: '毕业照约拍',
    enTitle: 'Graduation session',
  },
  {
    src: '/images/portfolio/private-024.jpg',
    category: 'private',
    subcategoryKey: '26-5-7-谢礼谦-个人-unsw毕业照约拍',
    subcategoryZh: '26 5 7 谢礼谦 个人 UNSW毕业照约拍',
    subcategoryEn: 'UNSW graduation session',
    zhTitle: '毕业照约拍',
    enTitle: 'Graduation session',
  },
  {
    src: '/images/portfolio/private-025.jpg',
    category: 'private',
    subcategoryKey: '26-5-7-谢礼谦-个人-unsw毕业照约拍',
    subcategoryZh: '26 5 7 谢礼谦 个人 UNSW毕业照约拍',
    subcategoryEn: 'UNSW graduation session',
    zhTitle: '毕业照约拍',
    enTitle: 'Graduation session',
  },
  {
    src: '/images/portfolio/private-026.jpg',
    category: 'private',
    subcategoryKey: '26-5-7-谢礼谦-个人-unsw毕业照约拍',
    subcategoryZh: '26 5 7 谢礼谦 个人 UNSW毕业照约拍',
    subcategoryEn: 'UNSW graduation session',
    zhTitle: '毕业照约拍',
    enTitle: 'Graduation session',
  },
  {
    src: '/images/portfolio/private-027.jpg',
    category: 'private',
    subcategoryKey: '26-5-7-谢礼谦-个人-unsw毕业照约拍',
    subcategoryZh: '26 5 7 谢礼谦 个人 UNSW毕业照约拍',
    subcategoryEn: 'UNSW graduation session',
    zhTitle: '毕业照约拍',
    enTitle: 'Graduation session',
  },
  {
    src: '/images/portfolio/private-036.webp',
    category: 'private',
    subcategoryKey: '26-5-9-中国花园-花开富贵-汉服',
    subcategoryZh: '26 5 9 中国花园 花开富贵 汉服',
    subcategoryEn: 'Chinese Garden Hanfu',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-037.webp',
    category: 'private',
    subcategoryKey: '26-5-9-中国花园-花开富贵-汉服',
    subcategoryZh: '26 5 9 中国花园 花开富贵 汉服',
    subcategoryEn: 'Chinese Garden Hanfu',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-038.webp',
    category: 'private',
    subcategoryKey: '26-5-9-中国花园-花开富贵-汉服',
    subcategoryZh: '26 5 9 中国花园 花开富贵 汉服',
    subcategoryEn: 'Chinese Garden Hanfu',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-039.webp',
    category: 'private',
    subcategoryKey: '26-5-9-中国花园-花开富贵-汉服',
    subcategoryZh: '26 5 9 中国花园 花开富贵 汉服',
    subcategoryEn: 'Chinese Garden Hanfu',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-040.webp',
    category: 'private',
    subcategoryKey: '26-5-9-中国花园-花开富贵-汉服',
    subcategoryZh: '26 5 9 中国花园 花开富贵 汉服',
    subcategoryEn: 'Chinese Garden Hanfu',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-041.webp',
    category: 'private',
    subcategoryKey: '26-5-9-中国花园-花开富贵-汉服',
    subcategoryZh: '26 5 9 中国花园 花开富贵 汉服',
    subcategoryEn: 'Chinese Garden Hanfu',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-042.webp',
    category: 'private',
    subcategoryKey: '26-5-9-中国花园-花开富贵-汉服',
    subcategoryZh: '26 5 9 中国花园 花开富贵 汉服',
    subcategoryEn: 'Chinese Garden Hanfu',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-043.webp',
    category: 'private',
    subcategoryKey: '26-5-9-中国花园-花开富贵-汉服',
    subcategoryZh: '26 5 9 中国花园 花开富贵 汉服',
    subcategoryEn: 'Chinese Garden Hanfu',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-044.webp',
    category: 'private',
    subcategoryKey: '26-5-9-中国花园-花开富贵-汉服',
    subcategoryZh: '26 5 9 中国花园 花开富贵 汉服',
    subcategoryEn: 'Chinese Garden Hanfu',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-045.webp',
    category: 'private',
    subcategoryKey: '26-5-9-中国花园-花开富贵-汉服',
    subcategoryZh: '26 5 9 中国花园 花开富贵 汉服',
    subcategoryEn: 'Chinese Garden Hanfu',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/private-046.webp',
    category: 'private',
    subcategoryKey: '26-5-9-中国花园-花开富贵-汉服',
    subcategoryZh: '26 5 9 中国花园 花开富贵 汉服',
    subcategoryEn: 'Chinese Garden Hanfu',
    zhTitle: '私人约拍作品',
    enTitle: 'Private session',
  },
  {
    src: '/images/portfolio/society-001.webp',
    category: 'society',
    subcategoryKey: '26-3-27-acisic-披萨',
    subcategoryZh: '26 3 27 acisic 披萨',
    subcategoryEn: 'ACISIC pizza event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-002.webp',
    category: 'society',
    subcategoryKey: '26-3-27-acisic-披萨',
    subcategoryZh: '26 3 27 acisic 披萨',
    subcategoryEn: 'ACISIC pizza event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-003.webp',
    category: 'society',
    subcategoryKey: '26-3-27-acisic-披萨',
    subcategoryZh: '26 3 27 acisic 披萨',
    subcategoryEn: 'ACISIC pizza event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-004.webp',
    category: 'society',
    subcategoryKey: '26-3-27-acisic-披萨',
    subcategoryZh: '26 3 27 acisic 披萨',
    subcategoryEn: 'ACISIC pizza event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-005.webp',
    category: 'society',
    subcategoryKey: '26-3-7-penta-手工',
    subcategoryZh: '26 3 7 penta 手工',
    subcategoryEn: 'PENTA workshop',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-006.webp',
    category: 'society',
    subcategoryKey: '26-3-7-penta-手工',
    subcategoryZh: '26 3 7 penta 手工',
    subcategoryEn: 'PENTA workshop',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-007.webp',
    category: 'society',
    subcategoryKey: '26-3-7-penta-手工',
    subcategoryZh: '26 3 7 penta 手工',
    subcategoryEn: 'PENTA workshop',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-008.webp',
    category: 'society',
    subcategoryKey: '26-3-7-penta-手工',
    subcategoryZh: '26 3 7 penta 手工',
    subcategoryEn: 'PENTA workshop',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-010.webp',
    category: 'society',
    subcategoryKey: '26-3-7-penta-手工',
    subcategoryZh: '26 3 7 penta 手工',
    subcategoryEn: 'PENTA workshop',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-011.webp',
    category: 'society',
    subcategoryKey: '26-4-3-penta-彩蛋',
    subcategoryZh: '26 4 3 penta 彩蛋',
    subcategoryEn: 'PENTA egg event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-012.webp',
    category: 'society',
    subcategoryKey: '26-4-3-penta-彩蛋',
    subcategoryZh: '26 4 3 penta 彩蛋',
    subcategoryEn: 'PENTA egg event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-013.webp',
    category: 'society',
    subcategoryKey: '26-4-3-penta-彩蛋',
    subcategoryZh: '26 4 3 penta 彩蛋',
    subcategoryEn: 'PENTA egg event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-014.webp',
    category: 'society',
    subcategoryKey: '26-4-3-penta-彩蛋',
    subcategoryZh: '26 4 3 penta 彩蛋',
    subcategoryEn: 'PENTA egg event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-015.webp',
    category: 'society',
    subcategoryKey: '26-4-3-penta-彩蛋',
    subcategoryZh: '26 4 3 penta 彩蛋',
    subcategoryEn: 'PENTA egg event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-016.webp',
    category: 'society',
    subcategoryKey: '26-4-3-penta-彩蛋',
    subcategoryZh: '26 4 3 penta 彩蛋',
    subcategoryEn: 'PENTA egg event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-017.webp',
    category: 'society',
    subcategoryKey: '26-4-3-penta-彩蛋',
    subcategoryZh: '26 4 3 penta 彩蛋',
    subcategoryEn: 'PENTA egg event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-018.webp',
    category: 'society',
    subcategoryKey: '26-4-3-penta-彩蛋',
    subcategoryZh: '26 4 3 penta 彩蛋',
    subcategoryEn: 'PENTA egg event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-019.webp',
    category: 'society',
    subcategoryKey: '26-4-3-penta-彩蛋',
    subcategoryZh: '26 4 3 penta 彩蛋',
    subcategoryEn: 'PENTA egg event',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-020.webp',
    category: 'society',
    subcategoryKey: '26-5-9-penta-团建-晚-调酒',
    subcategoryZh: '26 5 9 penta 团建 晚 调酒',
    subcategoryEn: 'PENTA cocktail gathering',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-021.webp',
    category: 'society',
    subcategoryKey: '26-5-9-penta-团建-晚-调酒',
    subcategoryZh: '26 5 9 penta 团建 晚 调酒',
    subcategoryEn: 'PENTA cocktail gathering',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-022.webp',
    category: 'society',
    subcategoryKey: '26-5-9-penta-团建-晚-调酒',
    subcategoryZh: '26 5 9 penta 团建 晚 调酒',
    subcategoryEn: 'PENTA cocktail gathering',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-023.webp',
    category: 'society',
    subcategoryKey: '26-5-9-penta-团建-晚-调酒',
    subcategoryZh: '26 5 9 penta 团建 晚 调酒',
    subcategoryEn: 'PENTA cocktail gathering',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-024.webp',
    category: 'society',
    subcategoryKey: '26-5-9-penta-团建-晚-调酒',
    subcategoryZh: '26 5 9 penta 团建 晚 调酒',
    subcategoryEn: 'PENTA cocktail gathering',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-025.webp',
    category: 'society',
    subcategoryKey: '26-5-9-penta-团建-晚-调酒',
    subcategoryZh: '26 5 9 penta 团建 晚 调酒',
    subcategoryEn: 'PENTA cocktail gathering',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-026.webp',
    category: 'society',
    subcategoryKey: '26-5-9-penta-团建-晚-调酒',
    subcategoryZh: '26 5 9 penta 团建 晚 调酒',
    subcategoryEn: 'PENTA cocktail gathering',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/society-027.webp',
    category: 'society',
    subcategoryKey: '26-5-9-penta-团建-晚-调酒',
    subcategoryZh: '26 5 9 penta 团建 晚 调酒',
    subcategoryEn: 'PENTA cocktail gathering',
    zhTitle: '社团活动记录',
    enTitle: 'Society event coverage',
  },
  {
    src: '/images/portfolio/commercial-001.webp',
    category: 'commercial',
    subcategoryKey: '26-4-30-晚宴-澳洲移民公司',
    subcategoryZh: '26 4 30 晚宴 澳洲移民公司',
    subcategoryEn: 'Migration agency dinner',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-002.webp',
    category: 'commercial',
    subcategoryKey: '26-4-30-晚宴-澳洲移民公司',
    subcategoryZh: '26 4 30 晚宴 澳洲移民公司',
    subcategoryEn: 'Migration agency dinner',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-003.webp',
    category: 'commercial',
    subcategoryKey: '26-4-30-晚宴-澳洲移民公司',
    subcategoryZh: '26 4 30 晚宴 澳洲移民公司',
    subcategoryEn: 'Migration agency dinner',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-004.webp',
    category: 'commercial',
    subcategoryKey: '26-4-30-晚宴-澳洲移民公司',
    subcategoryZh: '26 4 30 晚宴 澳洲移民公司',
    subcategoryEn: 'Migration agency dinner',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-005.webp',
    category: 'commercial',
    subcategoryKey: '26-4-30-晚宴-澳洲移民公司',
    subcategoryZh: '26 4 30 晚宴 澳洲移民公司',
    subcategoryEn: 'Migration agency dinner',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-006.webp',
    category: 'commercial',
    subcategoryKey: '26-5-1-dy-总部合作',
    subcategoryZh: '26 5 1 dy 总部合作',
    subcategoryEn: 'DY HQ collaboration',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-007.webp',
    category: 'commercial',
    subcategoryKey: '26-5-1-dy-总部合作',
    subcategoryZh: '26 5 1 dy 总部合作',
    subcategoryEn: 'DY HQ collaboration',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-008.webp',
    category: 'commercial',
    subcategoryKey: '26-5-1-dy-总部合作',
    subcategoryZh: '26 5 1 dy 总部合作',
    subcategoryEn: 'DY HQ collaboration',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-009.webp',
    category: 'commercial',
    subcategoryKey: '26-5-1-dy-总部合作',
    subcategoryZh: '26 5 1 dy 总部合作',
    subcategoryEn: 'DY HQ collaboration',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-010.webp',
    category: 'commercial',
    subcategoryKey: '26-5-1-dy-总部合作',
    subcategoryZh: '26 5 1 dy 总部合作',
    subcategoryEn: 'DY HQ collaboration',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-011.webp',
    category: 'commercial',
    subcategoryKey: '26-5-17elsa-混沌商学-救急拍摄',
    subcategoryZh: '26 5 17Elsa｜混沌商学 救急拍摄',
    subcategoryEn: 'Chaos Business School session',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-012.webp',
    category: 'commercial',
    subcategoryKey: '26-5-17elsa-混沌商学-救急拍摄',
    subcategoryZh: '26 5 17Elsa｜混沌商学 救急拍摄',
    subcategoryEn: 'Chaos Business School session',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-013.webp',
    category: 'commercial',
    subcategoryKey: '26-5-17elsa-混沌商学-救急拍摄',
    subcategoryZh: '26 5 17Elsa｜混沌商学 救急拍摄',
    subcategoryEn: 'Chaos Business School session',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-014.webp',
    category: 'commercial',
    subcategoryKey: '26-5-17elsa-混沌商学-救急拍摄',
    subcategoryZh: '26 5 17Elsa｜混沌商学 救急拍摄',
    subcategoryEn: 'Chaos Business School session',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-015.webp',
    category: 'commercial',
    subcategoryKey: '26-5-17elsa-混沌商学-救急拍摄',
    subcategoryZh: '26 5 17Elsa｜混沌商学 救急拍摄',
    subcategoryEn: 'Chaos Business School session',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-016.webp',
    category: 'commercial',
    subcategoryKey: '26-5-17elsa-混沌商学-救急拍摄',
    subcategoryZh: '26 5 17Elsa｜混沌商学 救急拍摄',
    subcategoryEn: 'Chaos Business School session',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-017.webp',
    category: 'commercial',
    subcategoryKey: '26-5-17elsa-混沌商学-救急拍摄',
    subcategoryZh: '26 5 17Elsa｜混沌商学 救急拍摄',
    subcategoryEn: 'Chaos Business School session',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-018.webp',
    category: 'commercial',
    subcategoryKey: '26-5-17elsa-混沌商学-救急拍摄',
    subcategoryZh: '26 5 17Elsa｜混沌商学 救急拍摄',
    subcategoryEn: 'Chaos Business School session',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-019.webp',
    category: 'commercial',
    subcategoryKey: '26-5-17elsa-混沌商学-救急拍摄',
    subcategoryZh: '26 5 17Elsa｜混沌商学 救急拍摄',
    subcategoryEn: 'Chaos Business School session',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-020.webp',
    category: 'commercial',
    subcategoryKey: '26-5-17elsa-混沌商学-救急拍摄',
    subcategoryZh: '26 5 17Elsa｜混沌商学 救急拍摄',
    subcategoryEn: 'Chaos Business School session',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/commercial-021.webp',
    category: 'commercial',
    subcategoryKey: '26-5-17elsa-混沌商学-救急拍摄',
    subcategoryZh: '26 5 17Elsa｜混沌商学 救急拍摄',
    subcategoryEn: 'Chaos Business School session',
    zhTitle: '商拍作品',
    enTitle: 'Commercial work',
  },
  {
    src: '/images/portfolio/city-001.webp',
    category: 'city',
    subcategoryKey: '城市风光',
    subcategoryZh: '城市风光',
    subcategoryEn: 'City landscapes',
    zhTitle: '悉尼城市风光',
    enTitle: 'Sydney cityscape',
  },
  {
    src: '/images/portfolio/city-002.webp',
    category: 'city',
    subcategoryKey: '城市风光',
    subcategoryZh: '城市风光',
    subcategoryEn: 'City landscapes',
    zhTitle: '悉尼城市风光',
    enTitle: 'Sydney cityscape',
  },
  {
    src: '/images/portfolio/city-003.webp',
    category: 'city',
    subcategoryKey: '城市风光',
    subcategoryZh: '城市风光',
    subcategoryEn: 'City landscapes',
    zhTitle: '悉尼城市风光',
    enTitle: 'Sydney cityscape',
  },
]
